{
 "title": "CNAND ND064 Observability Project Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "CPU Utilization Rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=~\"backend|frontend|trial\"}[$__interval])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU Load [1m]",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "increase(container_cpu_usage_seconds_total{container=~\"backend|frontend|trial\"}[1m])",
     "legendFormat": "{{container}}"
    },
    {}
   ]
  },
  {
   "title": "Memory Utilization Rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_memory_usage_bytes{container=~\"backend|frontend|trial\"}[$__interval])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage [1min]",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(container_memory_usage_bytes{container=~\"backend|frontend|trial\"}[1m])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Uptime Frontend Service",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(up{container=~\"frontend\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Uptime Backend Service",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "sum(up{container=~\"backend\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Uptime Trial Service ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "sum(up{container=~\"trial\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Requests Rate (per second)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{container=~\"backend|frontend|trial\"}[30s])) by (container,exported_endpoint)"
    }
   ]
  },
  {
   "title": "Number of Requests [1m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(flask_http_request_total[1m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Average response time [30s]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"200\"}[30s])\n/\nrate(flask_http_request_duration_seconds_count{status=\"200\"}[30s])",
     "legendFormat": "{{ exported_endpoint }}"
    }
   ]
  },
  {
   "title": "Error Rate  (per second)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{container=~\"backend|frontend|trial\", status!=\"200\"}[30s])) by (status,container,exported_endpoint)"
    }
   ]
  },
  {
   "title": "Number of Errors (Per Minute)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(flask_http_request_total{container=~\"backend|frontend|trial\", status!=\"200\"}[1m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Request Duration [30sec]  [p100]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, rate(flask_http_request_duration_seconds_bucket{status=\"200\"}[30s]))",
     "legendFormat": "{{ exported_endpoint}} "
    }
   ]
  }
 ]
}