{
 "title": "Initial Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Uptime Frontend Service",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(up{container=~\"frontend\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Uptime Backend Service",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(up{container=~\"backend\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Uptime Trial Service ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(up{container=~\"trial\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Error Rate  (per second)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{container=~\"backend|frontend|trial\", status!=\"200\"}[30s])) by (status,container,exported_endpoint)"
    }
   ]
  },
  {
   "title": "Error Rate  (per second)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{container=~\"backend|frontend|trial\", status!=\"200\"}[30s])) by (status,container,exported_endpoint)"
    }
   ]
  }
 ]
}